package hu.ait.shoppinglist.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// This annotation marks the class as an entity that will be stored in the database with the table name "shoppingitem"
@Entity(tableName = "shoppingitem")

// This is a data class that represents a shopping item
data class ShoppingItem (

    // This annotation marks the variable as the primary key of the entity and indicates that the value will not be autogenerated
    @PrimaryKey(autoGenerate = false) var name: String,

    // This annotation indicates that the variable will be stored in the database as a column named "price"
    @ColumnInfo(name = "price") var price: Int,

    // This annotation indicates that the variable will be stored in the database as a column named "description"
    @ColumnInfo(name = "description") var description: String,

    // This annotation indicates that the variable will be stored in the database as a column named "isbought"
    @ColumnInfo(name = "isbought") var bought: Boolean,

    // This annotation indicates that the variable will be stored in the database as a column named "category"
    @ColumnInfo(name = "category") var category: Int
): java.io.Serializable // This indicates that the class can be serialized for passing it between activities or fragments